---
name: 刀 Day Ahead Optimization
version: "0.4.58"
slug: day_ahead_opt
description: Docker used by Home Assistant Community Add-ons for day ahead optimizations
url: https://github.com/corneel27/day-ahead/
arch:
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 5000
apparmor: true
legacy: true
map:
  - ssl:rw
  - addon_config:rw
homeassistant_api: true
ports:
  5000/tcp: 5000

