---
name: Day Ahead Optimalisatie
version: "0.3.30"
slug: day_ahead_opt
description: Docker used by Home Assistant Community Add-ons for day ahead optimalisations
url: https://github.com/corneel27/day-ahead/
arch:
  - aarch64
init: false
map:
  - ssl:rw
  - addon_config:rw
  - share:rw
hassio_api: true
ports:
  5000/tcp: 5000

